# Fetching the latest node image on apline linux
FROM node:alpine AS development

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /react_template_2022

# Installing dependencies
COPY ./package.json /react_template_2022
RUN npm install

# Copying all the files in our project
COPY . .

# Starting the application
CMD npm start